title:              Something New
email:              nkhatun1411@gmail.com
description:        As New Is Always Better...
author:             Najma Khatun
baseurl:            ""
url:                "https://nkhatun.github.io"

# Social Profiles
github_username: nkhatun
linkedin_username: najma-khatun-211b0a102

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
